const KEY='aghsatman_v1';let data=JSON.parse(localStorage.getItem(KEY)||'{"items":[],"paid":[]}');
const faMonths=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
function pad(n){return String(n).padStart(2,'0')}
function jalaliToDate(s){let [jy,jm,jd]=s.split('/').map(Number);let gy=jy+621;let march=(jm<=10)?21:20;let d=new Date(gy,march-1,1);d.setDate(d.getDate()+((jm-1)*30)+jd-1);return d}
function dateToFa(d){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function nextDue(item){let start=jalaliToDate(item.start), now=new Date();for(let i=0;i<item.count;i++){let d=new Date(start);d.setMonth(d.getMonth()+i);d.setDate(Math.min(item.day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));if(d>=new Date(now.getFullYear(),now.getMonth(),now.getDate()))return {date:d,i};}return null}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function money(n){return Number(n).toLocaleString('fa-IR')+' تومان'}
function render(){let upcoming=data.items.map(x=>({x,d:nextDue(x)})).filter(a=>a.d).sort((a,b)=>a.d.date-b.d.date);let n=upcoming[0];nextTitle.textContent=n?.x.name||'-';nextAmount.textContent=n?money(n.x.amount):'-';nextDate.textContent=n?dateToFa(n.d.date):'-';list.innerHTML=upcoming.map(a=>`<div class="card"><div><b>${a.x.name}</b><div class="muted">${dateToFa(a.d.date)} · ${a.d.i+1} از ${a.x.count}</div></div><div><div class="amount">${money(a.x.amount)}</div><button onclick="pay('${a.x.id}')">پرداخت شد</button></div></div>`).join('')||'<p class="muted">قسطی ثبت نشده.</p>';paidList.innerHTML=data.paid.slice(-20).reverse().map(p=>`<div class="card"><div><b>${p.name}</b><div class="muted">${p.date}</div></div><div class="amount">${money(p.amount)}</div></div>`).join('')||'<p class="muted">هنوز پرداختی ثبت نشده.</p>'}
function pay(id){let x=data.items.find(a=>a.id===id),d=nextDue(x);if(!x||!d)return;data.paid.push({name:x.name,amount:x.amount,date:dateToFa(new Date())});x.count--;x.start=dateToFa(d.date);if(x.count<=0)data.items=data.items.filter(a=>a.id!==id);save()}
addBtn.onclick=()=>formDlg.showModal();form.onsubmit=e=>{e.preventDefault();data.items.push({id:crypto.randomUUID(),name:name.value,amount:Number(amount.value),day:Number(day.value),start:start.value,count:Number(count.value)});formDlg.close();form.reset();save()};notifyBtn.onclick=async()=>{if(!('Notification'in window)){alert('مرورگر این قابلیت را ندارد.');return}let p=await Notification.requestPermission();alert(p==='granted'?'اعلان‌ها فعال شد.':'اجازه اعلان داده نشد.')};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');